### ISSUE TITLE
Installing bug

### ISSUE THREAD

**Issue by UsamaKarim** [leandrosa81/taskbar-monitor#23]
While installing the latest version from releases it gives the following error.

I tried to install it again, my taskbar closes and I am not able to see the taskbar without a restart

Windows version `Microsoft Windows [Version 10.0.19042.1052]`
```
Unhandled Exception: System.IO.FileNotFoundException: Could not find file 'TaskbarMonitorInstaller.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at TaskbarMonitorInstaller.Program.<>c__DisplayClass3_0.<Install>b__0()
   at TaskbarMonitorInstaller.BLL.RestartExplorer.Execute(Action action)
   at TaskbarMonitorInstaller.Program.Install(InstallInfo info)
   at TaskbarMonitorInstaller.Program.Main(String[] args)
```

**Comment by KoalaBear84** [comment]
I've noticed this too when the installer is not named "TaskbarMonitorInstaller.exe", also happens when you download it multiple times when it automatically becomes like "TaskbarMonitorInstaller (1).exe".

It should be fixed when #15 is merged which already solved this issue. It's in this commit: https://github.com/leandrosa81/taskbar-monitor/pull/15/commits/4206a13c82fed3e3ed3ba9d9ceff8217fa8efe35
