### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by hungtrieu07** [leandrosa81/taskbar-monitor#48]
I just downloaded the exe file and run, but it response to me an error like this:

```
Installing taskbar-monitor on your computer, please wait.
Copying TaskbarMonitor.dll... OK.
Copying Newtonsoft.Json.dll... OK.
Copying TaskbarMonitorWindows11.exe... OK.
Copying TaskbarMonitorInstaller.exe...
Unhandled Exception: System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\TaskbarMonitor\TaskbarMonitorInstaller.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.File.InternalWriteAllBytes(String path, Byte[] bytes, Boolean checkHost)
   at System.IO.File.WriteAllBytes(String path, Byte[] bytes)
   at TaskbarMonitorInstaller.Program.<>c__DisplayClass3_0.<Install>b__0()
   at TaskbarMonitorInstaller.BLL.RestartExplorer.Execute(Action action)
   at TaskbarMonitorInstaller.Program.Install(InstallInfo info)
   at TaskbarMonitorInstaller.Program.Main(String[] args)
```

After that the command prompt window closed unexpected and the explorer.exe process has been killed.

**Comment by sengiv** [comment]
`... because it is being used by another process.`
2 instance is running, check hidden taskbar
