### ISSUE TITLE
not working in windows 11

### ISSUE THREAD

**Issue by AlizerUncaged** [leandrosa81/taskbar-monitor#49]
nothing shows up in windows 11 after install
![image](https://github.com/leandrosa81/taskbar-monitor/assets/86959368/c33abd0f-62ea-444e-852d-8e6d3fcdb8af)

**Comment by leandrosa81** [comment]
Did you reinstall the taskbar-monitor app? The Windows 11 executable is different, and the detection is made upon install.

**Comment by AlizerUncaged** [comment]
yes I did and no overlays in the taskbar
![image](https://github.com/leandrosa81/taskbar-monitor/assets/86959368/dc4fea54-4b13-4ca5-9042-092db64c9f96)

**Comment by AlizerUncaged** [comment]
alright so I did some changes in the code and looks like it gets moved to the back of the Taskbar as well as the Taskbar blur is getting applied to it

**Comment by sengiv** [comment]
@AlizerUncaged did you get it working?

**Comment by AlizerUncaged** [comment]
> @AlizerUncaged did you get it working?

not the taskbar monitor but i implemented my own taskbar widget for my company, i can show you the code if you're interested

**Comment by sengiv** [comment]
@AlizerUncaged I was hoping you got "taskbar-monitor" working for Windows 11
Does your widget for your company show CPU or RAM use percentage?
Please share the code, maybe it can be used to fix "taskbar-monitor" in Windows 11

**Comment by ncaq** [comment]
I also tried a new Windows 11 install, but the taskbar widget did not work.

**Comment by bolokhej** [comment]
It worked on win10, but on 11 only icon.
![Taskbar fail](https://github.com/leandrosa81/taskbar-monitor/assets/77867267/f57bfc01-3cee-4148-adea-3e8d8b844efb)

**Comment by DanielChrome** [comment]
Any update?

**Comment by veselaci** [comment]
I installed in Win11 ExplorerPatcher (https://github.com/valinet, https://valinet.ro/) and reconfigured the appearance on W10. Then I installed taskbar-monitor. So far functional and OK.

**Comment by xX-MrN0b0dy-Xx** [comment]
I confirm that on Windows 11 Pro 23H2 only an icon is shown in taskbar and nothing else... When you are in the settings the preview works like a charm but it doesn't work in the taskbar

**Comment by iggySeawolf** [comment]
The widget is also not displaying normally on my Windows 11 laptop. However, the widget is actually displaying - I found it when switching over virtual desktops using touchpad swipe gesture.
![image](https://github.com/leandrosa81/taskbar-monitor/assets/65216686/3a528169-a41b-43c5-9af4-d55f2e472807)

**Comment by akintelligentmedia** [comment]
In my case there was an error while running the application for the first time:

```Version: 1.0.0.0
Date: 9/4/2024
Time: 10:06:20

Exception:
 Category does not exist.
Source:
 System
Target site:
 CounterExists
Stack trace:
    at System.Diagnostics.PerformanceCounterLib.CounterExists(String machine, String category, String counter)
   at System.Diagnostics.PerformanceCounter.InitializeImpl()
   at System.Diagnostics.PerformanceCounter..ctor(String categoryName, String counterName, String instanceName, Boolean readOnly)
   at TaskbarMonitor.Counters.CounterCPU.Initialize()
   at TaskbarMonitor.Monitor.UpdateOptions(Options opt)
   at TaskbarMonitor.Monitor..ctor(Options opt)
   at TaskbarMonitorWindows11.Program.Main()```

No icon appear on the taskbar!

Run as normal user who is local administrator and as administrator as well but both of them gave the error above.

**Comment by vrykolas654** [comment]
I was able to get it working on Windows11 with multi-monitor. I had to set the following in TaskbarMonitor by setting "Enable taskbar-monitor on all taskbars":
I also had to disable the Windows settings for: Personalization > Taskbar > Taskbar behaviors:
![taskbar-monitor setings](https://github.com/leandrosa81/taskbar-monitor/assets/54197804/6943437a-5167-4732-8533-63f52b935802)
![Taskbar settings](https://github.com/leandrosa81/taskbar-monitor/assets/54197804/ecb49961-38ed-471c-849a-bbf6990de1c5)

**Comment by bolokhej** [comment]
Version 0.4.2 resolved my problem and it works fine on win11. Thanks.

**Comment by seniru-dilmith** [comment]
> I installed in Win11 ExplorerPatcher (https://github.com/valinet, https://valinet.ro/) and reconfigured the appearance on W10. Then I installed taskbar-monitor. So far functional and OK.

This didn't helped me in this matter. But this is a cool feature. This is more customizable.

**Comment by KoalaBear84** [comment]
Hmm, I thought there was no possible way to support Windows 11. But.. it looks like something is definately possible.

https://www.softperfect.com/products/networx/

![Image](https://github.com/user-attachments/assets/d4f88a05-d831-4977-9965-030d90c2e34f)

**Comment by KoalaBear84** [comment]
After I installed taskbar-monitor on Windows 11 I got the same issue as in other tickets.

```
Version: 1.0.0.0
Date: 4/3/2025
Time: 5:01:54 AM

Exception:
 Value was either too large or too small for an Int32.
Source:
 mscorlib
Target site:
 ToInt32
Stack trace:
    at System.Convert.ToInt32(Double value)
   at TaskbarMonitor.SystemWatcherControl.drawGraph(Graphics formGraphics, Int32 x, Int32 y, Int32 maxH, Boolean invertido, CounterInfo info, GraphTheme theme, CounterOptions opt)
   at TaskbarMonitor.SystemWatcherControl.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.UserControl.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

And it shows like this:

![Image](https://github.com/user-attachments/assets/4240b111-93d3-45ee-8207-c39575bb4399)
